# Generated by Django 5.1.1 on 2024-09-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=30),
        ),
    ]
